// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.V1.Db;

namespace backend.Migrations
{
    [DbContext(typeof(ClimbContext))]
    [Migration("20190418110908_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085");

            modelBuilder.Entity("backend.V1.Climb.Climb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CoordinatesId");

                    b.Property<string>("Grade");

                    b.Property<string>("ImageLocation");

                    b.Property<int?>("LocationId");

                    b.Property<string>("Name");

                    b.Property<string>("Notes");

                    b.Property<decimal>("Rating");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatesId");

                    b.HasIndex("LocationId");

                    b.ToTable("Climbs");
                });

            modelBuilder.Entity("backend.V1.Climb.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("Coordinate");
                });

            modelBuilder.Entity("backend.V1.Climb.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("backend.V1.Climb.Climb", b =>
                {
                    b.HasOne("backend.V1.Climb.Coordinate", "Coordinates")
                        .WithMany()
                        .HasForeignKey("CoordinatesId");

                    b.HasOne("backend.V1.Climb.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
